
import React from 'react';

const TermsAndConditionsPage = () => {
  return (
    <div className="container mx-auto max-w-4xl py-8 px-4 sm:px-6 lg:px-8 bg-white dark:bg-slate-800 rounded-lg shadow-md">
      <h1 className="text-3xl font-bold mb-6 text-slate-900 dark:text-white">Terms and Conditions</h1>
      <div className="space-y-4 text-slate-700 dark:text-slate-300">
        <p><strong>Last Updated:</strong> {new Date().toLocaleDateString()}</p>
        
        <p>Please read these Terms and Conditions ("Terms", "Terms and Conditions") carefully before using the AI Read-to-Earn mobile application (the "Service") operated by us.</p>
        <p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who wish to access or use the Service.</p>
        
        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">1. The Service</h2>
        <p>AI Read-to-Earn provides AI-generated stories for users to read. Users can earn "Points" for reading and engaging with the app. These points can be spent within the app or redeemed for monetary value under specific conditions.</p>
        
        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">2. Earning and Spending Points</h2>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>Users earn one (1) Point for each new page read. A page is considered "read" after a brief, predetermined time has passed on that page.</li>
          <li>Users must spend five (5) Points to unlock every subsequent set of five (5) pages of a story.</li>
          <li>Points have no cash value until redeemed through the official payout process.</li>
          <li>We reserve the right to change the rates for earning, spending, or redeeming points at any time.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">3. Payouts and Redemption</h2>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>The conversion rate for redemption is 1000 Points = ₹1 (Indian Rupee).</li>
          <li>A minimum balance of 1000 Points (equivalent to ₹1) is required to be eligible for a payout request.</li>
          <li>All payout requests are subject to review and verification.</li>
          <li>Once a payout request is submitted and approved, the funds will be dispatched within fifteen (15) business days.</li>
          <li>We reserve the right to deny payout requests in cases of suspected fraud, abuse of the system, or violation of these Terms.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">4. Advertisements</h2>
        <p>The Service is supported by advertisements. By using the Service, you agree to view advertisements, which may include:</p>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>Banner ads displayed on various screens.</li>
          <li>Rewarded video ads, which are user-initiated to unlock content or receive bonuses.</li>
          <li>Interstitial ads, which may be shown at natural transition points in the application, such as returning to the home screen.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">5. Intellectual Property</h2>
        <p>The stories and content generated by the AI within the Service are provided for your personal, non-commercial use only. You may not reproduce, distribute, or create derivative works from the content without our express permission.</p>

        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">6. Termination</h2>
        <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
        
        <h2 className="text-2xl font-semibold mt-6 mb-2 text-slate-800 dark:text-slate-200">7. Changes to Terms</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions within the application.</p>
        
        <p className="mt-6 italic"><strong>Disclaimer:</strong> These are template Terms and Conditions and are not a substitute for legal advice. You should consult with a legal professional to ensure compliance with all applicable laws and regulations.</p>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;
